/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminLoginDTO
 */
export interface AdminLoginDTO {
  /**
   *
   * @type {string}
   * @memberof AdminLoginDTO
   */
  login: string;
  /**
   *
   * @type {string}
   * @memberof AdminLoginDTO
   */
  password: string;
}

export function AdminLoginDTOFromJSON(json: any): AdminLoginDTO {
  return AdminLoginDTOFromJSONTyped(json, false);
}

export function AdminLoginDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminLoginDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    login: json["login"],
    password: json["password"],
  };
}

export function AdminLoginDTOToJSON(value?: AdminLoginDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    login: value.login === undefined ? undefined : value.login,
    password: value.password === undefined ? undefined : value.password,
  };
}
