/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AppVersion
 */
export interface AppVersion {
  /**
   *
   * @type {string}
   * @memberof AppVersion
   */
  value: string;
}

export function AppVersionFromJSON(json: any): AppVersion {
  return AppVersionFromJSONTyped(json, false);
}

export function AppVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppVersion {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"],
  };
}

export function AppVersionToJSON(value?: AppVersion | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value === undefined ? undefined : value.value,
  };
}
