/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChangeEmailDTO
 */
export interface ChangeEmailDTO {
  /**
   *
   * @type {string}
   * @memberof ChangeEmailDTO
   */
  newEmail: string;
  /**
   *
   * @type {string}
   * @memberof ChangeEmailDTO
   */
  password: string;
}

export function ChangeEmailDTOFromJSON(json: any): ChangeEmailDTO {
  return ChangeEmailDTOFromJSONTyped(json, false);
}

export function ChangeEmailDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmailDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    newEmail: json["newEmail"],
    password: json["password"],
  };
}

export function ChangeEmailDTOToJSON(value?: ChangeEmailDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    newEmail: value.newEmail === undefined ? undefined : value.newEmail,
    password: value.password === undefined ? undefined : value.password,
  };
}
