/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CheckBlock
 */
export interface CheckBlock {
  /**
   *
   * @type {boolean}
   * @memberof CheckBlock
   */
  isBlocked: boolean;
}

export function CheckBlockFromJSON(json: any): CheckBlock {
  return CheckBlockFromJSONTyped(json, false);
}

export function CheckBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckBlock {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    isBlocked: json["isBlocked"],
  };
}

export function CheckBlockToJSON(value?: CheckBlock | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    isBlocked: value.isBlocked === undefined ? undefined : value.isBlocked,
  };
}
