/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CompactUserProfileDTO
 */
export interface CompactUserProfileDTO {
  /**
   *
   * @type {number}
   * @memberof CompactUserProfileDTO
   */
  id: number;
  /**
   *
   * @type {boolean}
   * @memberof CompactUserProfileDTO
   */
  online: boolean;
  /**
   *
   * @type {string}
   * @memberof CompactUserProfileDTO
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CompactUserProfileDTO
   */
  image?: string;
  /**
   *
   * @type {Date}
   * @memberof CompactUserProfileDTO
   */
  birthday?: Date;
  /**
   *
   * @type {number[]}
   * @memberof CompactUserProfileDTO
   */
  blocks: number[];
}

export function CompactUserProfileDTOFromJSON(json: any): CompactUserProfileDTO {
  return CompactUserProfileDTOFromJSONTyped(json, false);
}

export function CompactUserProfileDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompactUserProfileDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    online: json["online"],
    name: json["name"],
    image: !exists(json, "image") ? undefined : json["image"],
    birthday: !exists(json, "birthday") ? undefined : new Date(json["birthday"]),
    blocks: json["blocks"],
  };
}

export function CompactUserProfileDTOToJSON(value?: CompactUserProfileDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? undefined : value.id,
    online: value.online === undefined ? undefined : value.online,
    name: value.name === undefined ? undefined : value.name,
    image: value.image === undefined ? undefined : value.image,
    birthday: value.birthday === undefined ? undefined : value.birthday.toISOString(),
    blocks: value.blocks === undefined ? undefined : value.blocks,
  };
}
