/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EmailNotificationEntity
 */
export interface EmailNotificationEntity {
  /**
   *
   * @type {boolean}
   * @memberof EmailNotificationEntity
   */
  digest: boolean;
}

export function EmailNotificationEntityFromJSON(json: any): EmailNotificationEntity {
  return EmailNotificationEntityFromJSONTyped(json, false);
}

export function EmailNotificationEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailNotificationEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    digest: json["digest"],
  };
}

export function EmailNotificationEntityToJSON(value?: EmailNotificationEntity | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    digest: value.digest === undefined ? undefined : value.digest,
  };
}
