/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  PublicUserProfileDTO,
  PublicUserProfileDTOFromJSON,
  PublicUserProfileDTOFromJSONTyped,
  PublicUserProfileDTOToJSON,
} from "./";

/**
 *
 * @export
 * @interface FriendshipDTO
 */
export interface FriendshipDTO {
  /**
   *
   * @type {PublicUserProfileDTO}
   * @memberof FriendshipDTO
   */
  user: PublicUserProfileDTO;
  /**
   *
   * @type {string}
   * @memberof FriendshipDTO
   */
  message?: string;
}

export function FriendshipDTOFromJSON(json: any): FriendshipDTO {
  return FriendshipDTOFromJSONTyped(json, false);
}

export function FriendshipDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendshipDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: PublicUserProfileDTOFromJSON(json["user"]),
    message: !exists(json, "message") ? undefined : json["message"],
  };
}

export function FriendshipDTOToJSON(value?: FriendshipDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    user: PublicUserProfileDTOToJSON(value.user),
    message: value.message === undefined ? undefined : value.message,
  };
}
