/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ImageEntityDTO
 */
export interface ImageEntityDTO {
  /**
   *
   * @type {string}
   * @memberof ImageEntityDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ImageEntityDTO
   */
  path: string;
  /**
   *
   * @type {string}
   * @memberof ImageEntityDTO
   */
  absolutePath: string;
}

export function ImageEntityDTOFromJSON(json: any): ImageEntityDTO {
  return ImageEntityDTOFromJSONTyped(json, false);
}

export function ImageEntityDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageEntityDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    path: json["path"],
    absolutePath: json["absolutePath"],
  };
}

export function ImageEntityDTOToJSON(value?: ImageEntityDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? undefined : value.id,
    path: value.path === undefined ? undefined : value.path,
    absolutePath: value.absolutePath === undefined ? undefined : value.absolutePath,
  };
}
