/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  PublicUserProfileDTO,
  PublicUserProfileDTOFromJSON,
  PublicUserProfileDTOFromJSONTyped,
  PublicUserProfileDTOToJSON,
} from "./";

/**
 *
 * @export
 * @interface IncomingFollowRequestDTO
 */
export interface IncomingFollowRequestDTO {
  /**
   *
   * @type {PublicUserProfileDTO}
   * @memberof IncomingFollowRequestDTO
   */
  from: PublicUserProfileDTO;
  /**
   *
   * @type {number}
   * @memberof IncomingFollowRequestDTO
   */
  id: number;
}

export function IncomingFollowRequestDTOFromJSON(json: any): IncomingFollowRequestDTO {
  return IncomingFollowRequestDTOFromJSONTyped(json, false);
}

export function IncomingFollowRequestDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IncomingFollowRequestDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    from: PublicUserProfileDTOFromJSON(json["from"]),
    id: json["id"],
  };
}

export function IncomingFollowRequestDTOToJSON(value?: IncomingFollowRequestDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    from: PublicUserProfileDTOToJSON(value.from),
    id: value.id === undefined ? undefined : value.id,
  };
}
