/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MoneyDto
 */
export interface MoneyDto {
  /**
   *
   * @type {string}
   * @memberof MoneyDto
   */
  currency: string;
  /**
   *
   * @type {number}
   * @memberof MoneyDto
   */
  amount: number;
}

export function MoneyDtoFromJSON(json: any): MoneyDto {
  return MoneyDtoFromJSONTyped(json, false);
}

export function MoneyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MoneyDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    currency: json["currency"],
    amount: json["amount"],
  };
}

export function MoneyDtoToJSON(value?: MoneyDto | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    currency: value.currency === undefined ? undefined : value.currency,
    amount: value.amount === undefined ? undefined : value.amount,
  };
}
