/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NotificationSettingsDTO
 */
export interface NotificationSettingsDTO {
  /**
   *
   * @type {boolean}
   * @memberof NotificationSettingsDTO
   */
  digest: boolean;
}

export function NotificationSettingsDTOFromJSON(json: any): NotificationSettingsDTO {
  return NotificationSettingsDTOFromJSONTyped(json, false);
}

export function NotificationSettingsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationSettingsDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    digest: json["digest"],
  };
}

export function NotificationSettingsDTOToJSON(value?: NotificationSettingsDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    digest: value.digest === undefined ? undefined : value.digest,
  };
}
