/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  PublicUserProfileDTO,
  PublicUserProfileDTOFromJSON,
  PublicUserProfileDTOFromJSONTyped,
  PublicUserProfileDTOToJSON,
} from "./";

/**
 *
 * @export
 * @interface PendingReviewDTO
 */
export interface PendingReviewDTO {
  /**
   *
   * @type {number}
   * @memberof PendingReviewDTO
   */
  id: number;
  /**
   *
   * @type {PublicUserProfileDTO}
   * @memberof PendingReviewDTO
   */
  companion: PublicUserProfileDTO;
}

export function PendingReviewDTOFromJSON(json: any): PendingReviewDTO {
  return PendingReviewDTOFromJSONTyped(json, false);
}

export function PendingReviewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingReviewDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    companion: PublicUserProfileDTOFromJSON(json["companion"]),
  };
}

export function PendingReviewDTOToJSON(value?: PendingReviewDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? undefined : value.id,
    companion: PublicUserProfileDTOToJSON(value.companion),
  };
}
