/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PrivacyEntity
 */
export interface PrivacyEntity {
  /**
   *
   * @type {string}
   * @memberof PrivacyEntity
   */
  photos: PrivacyEntityPhotosEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyEntity
   */
  profileInfo: PrivacyEntityProfileInfoEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyEntity
   */
  rating: PrivacyEntityRatingEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyEntity
   */
  statusMessage: PrivacyEntityStatusMessageEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyEntity
   */
  userPic: PrivacyEntityUserPicEnum;
}

export function PrivacyEntityFromJSON(json: any): PrivacyEntity {
  return PrivacyEntityFromJSONTyped(json, false);
}

export function PrivacyEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacyEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    photos: json["photos"],
    profileInfo: json["profileInfo"],
    rating: json["rating"],
    statusMessage: json["statusMessage"],
    userPic: json["userPic"],
  };
}

export function PrivacyEntityToJSON(value?: PrivacyEntity | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    photos: value.photos === undefined ? undefined : value.photos,
    profileInfo: value.profileInfo === undefined ? undefined : value.profileInfo,
    rating: value.rating === undefined ? undefined : value.rating,
    statusMessage: value.statusMessage === undefined ? undefined : value.statusMessage,
    userPic: value.userPic === undefined ? undefined : value.userPic,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum PrivacyEntityPhotosEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyEntityProfileInfoEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyEntityRatingEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyEntityStatusMessageEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyEntityUserPicEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
