/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PrivacyDTO
 */
export interface PrivacyDTO {
  /**
   *
   * @type {number}
   * @memberof PrivacyDTO
   */
  uid: number;
  /**
   *
   * @type {string}
   * @memberof PrivacyDTO
   */
  photos: PrivacyDTOPhotosEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyDTO
   */
  profileInfo: PrivacyDTOProfileInfoEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyDTO
   */
  rating: PrivacyDTORatingEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyDTO
   */
  statusMessage: PrivacyDTOStatusMessageEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyDTO
   */
  userPic: PrivacyDTOUserPicEnum;
}

export function PrivacyDTOFromJSON(json: any): PrivacyDTO {
  return PrivacyDTOFromJSONTyped(json, false);
}

export function PrivacyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacyDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uid: json["uid"],
    photos: json["photos"],
    profileInfo: json["profileInfo"],
    rating: json["rating"],
    statusMessage: json["statusMessage"],
    userPic: json["userPic"],
  };
}

export function PrivacyDTOToJSON(value?: PrivacyDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    uid: value.uid === undefined ? undefined : value.uid,
    photos: value.photos === undefined ? undefined : value.photos,
    profileInfo: value.profileInfo === undefined ? undefined : value.profileInfo,
    rating: value.rating === undefined ? undefined : value.rating,
    statusMessage: value.statusMessage === undefined ? undefined : value.statusMessage,
    userPic: value.userPic === undefined ? undefined : value.userPic,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum PrivacyDTOPhotosEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyDTOProfileInfoEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyDTORatingEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyDTOStatusMessageEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyDTOUserPicEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
