/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface QueuePreferenceDTO
 */
export interface QueuePreferenceDTO {
  /**
   *
   * @type {boolean}
   * @memberof QueuePreferenceDTO
   */
  near: boolean;
  /**
   *
   * @type {number}
   * @memberof QueuePreferenceDTO
   */
  ageTo: number;
  /**
   *
   * @type {number}
   * @memberof QueuePreferenceDTO
   */
  ageFrom: number;
  /**
   *
   * @type {boolean}
   * @memberof QueuePreferenceDTO
   */
  highRating: boolean;
  /**
   *
   * @type {string}
   * @memberof QueuePreferenceDTO
   */
  sex: QueuePreferenceDTOSexEnum;
}

export function QueuePreferenceDTOFromJSON(json: any): QueuePreferenceDTO {
  return QueuePreferenceDTOFromJSONTyped(json, false);
}

export function QueuePreferenceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueuePreferenceDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    near: json["near"],
    ageTo: json["ageTo"],
    ageFrom: json["ageFrom"],
    highRating: json["highRating"],
    sex: json["sex"],
  };
}

export function QueuePreferenceDTOToJSON(value?: QueuePreferenceDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    near: value.near === undefined ? undefined : value.near,
    ageTo: value.ageTo === undefined ? undefined : value.ageTo,
    ageFrom: value.ageFrom === undefined ? undefined : value.ageFrom,
    highRating: value.highRating === undefined ? undefined : value.highRating,
    sex: value.sex === undefined ? undefined : value.sex,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum QueuePreferenceDTOSexEnum {
  MALE = "MALE",
  FEMALE = "FEMALE",
  UNDEF = "UNDEF",
}
