/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
  /**
   *
   * @type {string}
   * @memberof RegisterDTO
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterDTO
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof RegisterDTO
   */
  name: string;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
  return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
    name: json["name"],
  };
}

export function RegisterDTOToJSON(value?: RegisterDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email === undefined ? undefined : value.email,
    password: value.password === undefined ? undefined : value.password,
    name: value.name === undefined ? undefined : value.name,
  };
}
