/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReportDTO
 */
export interface ReportDTO {
  /**
   *
   * @type {string}
   * @memberof ReportDTO
   */
  text: string;
}

export function ReportDTOFromJSON(json: any): ReportDTO {
  return ReportDTOFromJSONTyped(json, false);
}

export function ReportDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    text: json["text"],
  };
}

export function ReportDTOToJSON(value?: ReportDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    text: value.text === undefined ? undefined : value.text,
  };
}
