/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetNewPasswordDTO
 */
export interface SetNewPasswordDTO {
  /**
   *
   * @type {string}
   * @memberof SetNewPasswordDTO
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof SetNewPasswordDTO
   */
  password1: string;
  /**
   *
   * @type {string}
   * @memberof SetNewPasswordDTO
   */
  password2: string;
}

export function SetNewPasswordDTOFromJSON(json: any): SetNewPasswordDTO {
  return SetNewPasswordDTOFromJSONTyped(json, false);
}

export function SetNewPasswordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetNewPasswordDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json["code"],
    password1: json["password1"],
    password2: json["password2"],
  };
}

export function SetNewPasswordDTOToJSON(value?: SetNewPasswordDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code === undefined ? undefined : value.code,
    password1: value.password1 === undefined ? undefined : value.password1,
    password2: value.password2 === undefined ? undefined : value.password2,
  };
}
