/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SubmitIncomingRequestDTO
 */
export interface SubmitIncomingRequestDTO {
  /**
   *
   * @type {number}
   * @memberof SubmitIncomingRequestDTO
   */
  uid: number;
  /**
   *
   * @type {boolean}
   * @memberof SubmitIncomingRequestDTO
   */
  accept: boolean;
}

export function SubmitIncomingRequestDTOFromJSON(json: any): SubmitIncomingRequestDTO {
  return SubmitIncomingRequestDTOFromJSONTyped(json, false);
}

export function SubmitIncomingRequestDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubmitIncomingRequestDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uid: json["uid"],
    accept: json["accept"],
  };
}

export function SubmitIncomingRequestDTOToJSON(value?: SubmitIncomingRequestDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    uid: value.uid === undefined ? undefined : value.uid,
    accept: value.accept === undefined ? undefined : value.accept,
  };
}
