/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TokenHold
 */
export interface TokenHold {
  /**
   *
   * @type {string}
   * @memberof TokenHold
   */
  token: string;
}

export function TokenHoldFromJSON(json: any): TokenHold {
  return TokenHoldFromJSONTyped(json, false);
}

export function TokenHoldFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenHold {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    token: json["token"],
  };
}

export function TokenHoldToJSON(value?: TokenHold | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    token: value.token === undefined ? undefined : value.token,
  };
}
