/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateGeolocationDto
 */
export interface UpdateGeolocationDto {
  /**
   *
   * @type {number}
   * @memberof UpdateGeolocationDto
   */
  lon: number;
  /**
   *
   * @type {number}
   * @memberof UpdateGeolocationDto
   */
  lat: number;
}

export function UpdateGeolocationDtoFromJSON(json: any): UpdateGeolocationDto {
  return UpdateGeolocationDtoFromJSONTyped(json, false);
}

export function UpdateGeolocationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGeolocationDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lon: json["lon"],
    lat: json["lat"],
  };
}

export function UpdateGeolocationDtoToJSON(value?: UpdateGeolocationDto | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    lon: value.lon === undefined ? undefined : value.lon,
    lat: value.lat === undefined ? undefined : value.lat,
  };
}
