/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdatePrivacyDTO
 */
export interface UpdatePrivacyDTO {
  /**
   *
   * @type {string}
   * @memberof UpdatePrivacyDTO
   */
  photos?: UpdatePrivacyDTOPhotosEnum;
  /**
   *
   * @type {string}
   * @memberof UpdatePrivacyDTO
   */
  profileInfo?: UpdatePrivacyDTOProfileInfoEnum;
  /**
   *
   * @type {string}
   * @memberof UpdatePrivacyDTO
   */
  rating?: UpdatePrivacyDTORatingEnum;
  /**
   *
   * @type {string}
   * @memberof UpdatePrivacyDTO
   */
  statusMessage?: UpdatePrivacyDTOStatusMessageEnum;
  /**
   *
   * @type {string}
   * @memberof UpdatePrivacyDTO
   */
  userPic?: UpdatePrivacyDTOUserPicEnum;
}

export function UpdatePrivacyDTOFromJSON(json: any): UpdatePrivacyDTO {
  return UpdatePrivacyDTOFromJSONTyped(json, false);
}

export function UpdatePrivacyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePrivacyDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    photos: !exists(json, "photos") ? undefined : json["photos"],
    profileInfo: !exists(json, "profileInfo") ? undefined : json["profileInfo"],
    rating: !exists(json, "rating") ? undefined : json["rating"],
    statusMessage: !exists(json, "statusMessage") ? undefined : json["statusMessage"],
    userPic: !exists(json, "userPic") ? undefined : json["userPic"],
  };
}

export function UpdatePrivacyDTOToJSON(value?: UpdatePrivacyDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    photos: value.photos === undefined ? undefined : value.photos,
    profileInfo: value.profileInfo === undefined ? undefined : value.profileInfo,
    rating: value.rating === undefined ? undefined : value.rating,
    statusMessage: value.statusMessage === undefined ? undefined : value.statusMessage,
    userPic: value.userPic === undefined ? undefined : value.userPic,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum UpdatePrivacyDTOPhotosEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum UpdatePrivacyDTOProfileInfoEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum UpdatePrivacyDTORatingEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum UpdatePrivacyDTOStatusMessageEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
/**
 * @export
 * @enum {string}
 */
export enum UpdatePrivacyDTOUserPicEnum {
  EVERYONE = "EVERYONE",
  FRIENDS = "FRIENDS",
  NOBODY = "NOBODY",
}
