/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { UserEntity, UserEntityFromJSON, UserEntityFromJSONTyped, UserEntityToJSON } from "./";

/**
 *
 * @export
 * @interface UserConnectionEntity
 */
export interface UserConnectionEntity {
  /**
   *
   * @type {number}
   * @memberof UserConnectionEntity
   */
  id: number;
  /**
   *
   * @type {UserEntity}
   * @memberof UserConnectionEntity
   */
  user: UserEntity;
  /**
   *
   * @type {string}
   * @memberof UserConnectionEntity
   */
  externalId: string;
  /**
   *
   * @type {string}
   * @memberof UserConnectionEntity
   */
  social: UserConnectionEntitySocialEnum;
}

export function UserConnectionEntityFromJSON(json: any): UserConnectionEntity {
  return UserConnectionEntityFromJSONTyped(json, false);
}

export function UserConnectionEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConnectionEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    user: UserEntityFromJSON(json["user"]),
    externalId: json["externalId"],
    social: json["social"],
  };
}

export function UserConnectionEntityToJSON(value?: UserConnectionEntity | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? undefined : value.id,
    user: UserEntityToJSON(value.user),
    externalId: value.externalId === undefined ? undefined : value.externalId,
    social: value.social === undefined ? undefined : value.social,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum UserConnectionEntitySocialEnum {
  GOOGLE = "GOOGLE",
  VK = "VK",
  APPLE = "APPLE",
}
