/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { ImageEntity, ImageEntityFromJSON, ImageEntityFromJSONTyped, ImageEntityToJSON } from "./";

/**
 *
 * @export
 * @interface UserProfileEntity
 */
export interface UserProfileEntity {
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  sex: UserProfileEntitySexEnum;
  /**
   *
   * @type {ImageEntity}
   * @memberof UserProfileEntity
   */
  image?: ImageEntity;
  /**
   *
   * @type {Array<ImageEntity>}
   * @memberof UserProfileEntity
   */
  images: Array<ImageEntity>;
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  city?: string;
  /**
   *
   * @type {Date}
   * @memberof UserProfileEntity
   */
  birthday?: Date;
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof UserProfileEntity
   */
  descriptionPrivate?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserProfileEntity
   */
  tags: Array<string>;
  /**
   *
   * @type {number}
   * @memberof UserProfileEntity
   */
  rating?: number;
  /**
   *
   * @type {number}
   * @memberof UserProfileEntity
   */
  views: number;
  /**
   *
   * @type {number}
   * @memberof UserProfileEntity
   */
  lon?: number;
  /**
   *
   * @type {number}
   * @memberof UserProfileEntity
   */
  lat?: number;
  /**
   *
   * @type {boolean}
   * @memberof UserProfileEntity
   */
  hide?: boolean;
}

export function UserProfileEntityFromJSON(json: any): UserProfileEntity {
  return UserProfileEntityFromJSONTyped(json, false);
}

export function UserProfileEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    sex: json["sex"],
    image: !exists(json, "image") ? undefined : ImageEntityFromJSON(json["image"]),
    images: (json["images"] as Array<any>).map(ImageEntityFromJSON),
    country: !exists(json, "country") ? undefined : json["country"],
    city: !exists(json, "city") ? undefined : json["city"],
    birthday: !exists(json, "birthday") ? undefined : new Date(json["birthday"]),
    description: json["description"],
    status: json["status"],
    descriptionPrivate: !exists(json, "descriptionPrivate") ? undefined : json["descriptionPrivate"],
    tags: json["tags"],
    rating: !exists(json, "rating") ? undefined : json["rating"],
    views: json["views"],
    lon: !exists(json, "lon") ? undefined : json["lon"],
    lat: !exists(json, "lat") ? undefined : json["lat"],
    hide: json["hide"],
  };
}

export function UserProfileEntityToJSON(value?: UserProfileEntity | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name === undefined ? undefined : value.name,
    sex: value.sex === undefined ? undefined : value.sex,
    image: ImageEntityToJSON(value.image),
    images: ((value.images || []) as Array<any>).map(ImageEntityToJSON),
    country: value.country === undefined ? undefined : value.country,
    city: value.city === undefined ? undefined : value.city,
    birthday: value.birthday === undefined ? undefined : value.birthday.toISOString(),
    description: value.description === undefined ? undefined : value.description,
    status: value.status === undefined ? undefined : value.status,
    descriptionPrivate: value.descriptionPrivate === undefined ? undefined : value.descriptionPrivate,
    tags: value.tags === undefined ? undefined : value.tags,
    rating: value.rating === undefined ? undefined : value.rating,
    views: value.views === undefined ? undefined : value.views,
    lon: value.lon === undefined ? undefined : value.lon,
    lat: value.lat === undefined ? undefined : value.lat,
    hide: value.hide === undefined ? undefined : value.hide,
  };
}

/**
 * @export
 * @enum {string}
 */
export enum UserProfileEntitySexEnum {
  MALE = "MALE",
  FEMALE = "FEMALE",
  UNDEF = "UNDEF",
}
