/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { MoneyDto, MoneyDtoFromJSON, MoneyDtoFromJSONTyped, MoneyDtoToJSON } from "./";

/**
 *
 * @export
 * @interface VipPaymentDto
 */
export interface VipPaymentDto {
  /**
   *
   * @type {number}
   * @memberof VipPaymentDto
   */
  days: number;
  /**
   *
   * @type {number}
   * @memberof VipPaymentDto
   */
  date: number;
  /**
   *
   * @type {MoneyDto}
   * @memberof VipPaymentDto
   */
  amount: MoneyDto;
}

export function VipPaymentDtoFromJSON(json: any): VipPaymentDto {
  return VipPaymentDtoFromJSONTyped(json, false);
}

export function VipPaymentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VipPaymentDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    days: json["days"],
    date: json["date"],
    amount: MoneyDtoFromJSON(json["amount"]),
  };
}

export function VipPaymentDtoToJSON(value?: VipPaymentDto | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    days: value.days === undefined ? undefined : value.days,
    date: value.date === undefined ? undefined : value.date,
    amount: MoneyDtoToJSON(value.amount),
  };
}
