/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { MoneyDto, MoneyDtoFromJSON, MoneyDtoFromJSONTyped, MoneyDtoToJSON } from "./";

/**
 *
 * @export
 * @interface VipProductDTO
 */
export interface VipProductDTO {
  /**
   *
   * @type {number}
   * @memberof VipProductDTO
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof VipProductDTO
   */
  days: number;
  /**
   *
   * @type {MoneyDto}
   * @memberof VipProductDTO
   */
  amount: MoneyDto;
}

export function VipProductDTOFromJSON(json: any): VipProductDTO {
  return VipProductDTOFromJSONTyped(json, false);
}

export function VipProductDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VipProductDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    days: json["days"],
    amount: MoneyDtoFromJSON(json["amount"]),
  };
}

export function VipProductDTOToJSON(value?: VipProductDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? undefined : value.id,
    days: value.days === undefined ? undefined : value.days,
    amount: MoneyDtoToJSON(value.amount),
  };
}
