/* tslint:disable */
/* eslint-disable */
/**
 * Revolver API
 * Revolver API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { VipPaymentDto, VipPaymentDtoFromJSON, VipPaymentDtoFromJSONTyped, VipPaymentDtoToJSON } from "./";

/**
 *
 * @export
 * @interface VipStatusDTO
 */
export interface VipStatusDTO {
  /**
   *
   * @type {number}
   * @memberof VipStatusDTO
   */
  daysLeft: number;
  /**
   *
   * @type {boolean}
   * @memberof VipStatusDTO
   */
  active: boolean;
  /**
   *
   * @type {Array<VipPaymentDto>}
   * @memberof VipStatusDTO
   */
  payments: Array<VipPaymentDto>;
  /**
   *
   * @type {Date}
   * @memberof VipStatusDTO
   */
  endDate: Date;
}

export function VipStatusDTOFromJSON(json: any): VipStatusDTO {
  return VipStatusDTOFromJSONTyped(json, false);
}

export function VipStatusDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VipStatusDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    daysLeft: json["daysLeft"],
    active: json["active"],
    payments: (json["payments"] as Array<any>).map(VipPaymentDtoFromJSON),
    endDate: new Date(json["endDate"]),
  };
}

export function VipStatusDTOToJSON(value?: VipStatusDTO | null): any {
  if (value === undefined) {
    return null;
  }
  if (value === null) {
    return null;
  }
  return {
    daysLeft: value.daysLeft === undefined ? undefined : value.daysLeft,
    active: value.active === undefined ? undefined : value.active,
    payments: ((value.payments || []) as Array<any>).map(VipPaymentDtoToJSON),
    endDate: value.endDate.toISOString(),
  };
}
